### ISSUE TITLE
Scratch.gui.getBlockly() errors.

### ISSUE THREAD

**Issue by AshimeeAlt** [TurboWarp/scratch-gui#927]
### Expected Behavior

It should get blockly

### Actual Behavior

It throws an error saying `LazyScratchBlocks.onLoaded` is not a function.

A log snippet
```
11:29:15.649 Scratch.gui.getBlockly()
11:29:15.683 Promise {<rejected>: TypeError: re.a.onLoaded is not a function
    at https://staging.turbowarp.org/js/editor~embed~ful…}[[Prototype]]: Promise[[PromiseState]]: "rejected"[[PromiseResult]]: TypeError: re.a.onLoaded is not a function
    at https://staging.turbowarp.org/js/editor~embed~fullscreen~player.5a9777e2c59bace23510.js:1:130480
    at new Promise (<anonymous>)
    at Object.getBlockly (https://staging.turbowarp.org/js/editor~embed~fullscreen~player.5a9777e2c59bace23510.js:1:130459)
    at <anonymous>:1:13message: "re.a.onLoaded is not a function"stack: "TypeError: re.a.onLoaded is not a function\n    at https://staging.turbowarp.org/js/editor~embed~fullscreen~player.5a9777e2c59bace23510.js:1:130480\n    at new Promise (<anonymous>)\n    at Object.getBlockly (https://staging.turbowarp.org/js/editor~embed~fullscreen~player.5a9777e2c59bace23510.js:1:130459)\n    at <anonymous>:1:13"[[Prototype]]: Error
11:29:15.659 tw-extension-gui-api.js:19 Uncaught (in promise) TypeError: re.a.onLoaded is not a function
    at tw-extension-gui-api.js:19:68
    at new Promise (<anonymous>)
    at Object.getBlockly (tw-extension-gui-api.js:19:27)
    at <anonymous>:1:13
(anonymous) @ tw-extension-gui-api.js:19
getBlockly @ tw-extension-gui-api.js:19
(anonymous) @ VM141:1
```
I think this commit may have broke it https://github.com/TurboWarp/scratch-gui/commit/4d4a48e319234a556f544f4825f1dac7a7d680a9

### Steps to Reproduce

Load any extension and type in the console (while in the editor on staging.turbowarp.org) `Scratch.gui.getBlockly()`.

### Operating System and Browser

Raspberry PI 5, with Chromium Version 122.0.6261.89 (Official Build) Built on Debian , running on Debian 12 (64-bit)

**Comment by AshimeeAlt** [comment]
temporary patch for this exact thing:
```js
(function() {
  function getBlockly() {
    return new Promise((resolve_getBlockly, reject_getBlockly) => {
      // A single namespace as to not waste RAM with setTimeout loops
      if (!vm?.$LazySB) vm.$LazySB = {
        $dev: false,
        onBlockly(callback) {
          return new Promise((resolve_onBlockly, reject_onBlockly) => {
            if (typeof window?.ScratchBlocks === 'object') resolve_onBlockly(window.ScratchBlocks);
            function waitLoop() {
              if (vm.$LazySB.$dev) console.log('wait loop');
              if (typeof window?.ScratchBlocks !== 'object') {
                if (vm.$LazySB.$dev) console.log('looping again');
                setTimeout(() => waitLoop(), 10);
              } else {
                if (vm.$LazySB.$dev) console.log('Found Blockly, resolving onBlockly');
                callback(window.ScratchBlocks);
                resolve_onBlockly(window.ScratchBlocks);
              }
            }
            setTimeout(() => waitLoop(), 10);
          });
        },
        waitingForBlockly: false,
        getBlocklyCallbacks: []
      }
      const LazySB = vm.$LazySB;
      if (!LazySB.waitingForBlockly) {
        const LazySB = vm.$LazySB;
        if (LazySB.$dev) console.log('waiting for blockly');
        LazySB.onBlockly((Blockly) => {
          const LazySB = vm.$LazySB;
          if (LazySB.$dev) console.log('onBlockly callback called');
          while (LazySB.getBlocklyCallbacks.length > 0) {
            const callback = LazySB.getBlocklyCallbacks.shift();
            if (typeof callback === 'function') callback(Blockly);
          }
          LazySB.waitingForBlockly = false;
          if (LazySB.$dev) console.log('no longer waiting for Blockly');
        });
        LazySB.waitingForBlockly = true;
      }
      LazySB.getBlocklyCallbacks.push(function(Blockly) {
        resolve_getBlockly(Blockly);
      });
    });
  }
  if (!Scratch?.gui) Scratch.gui = Scratch?.gui ?? {
    getBlockly,
    getBlocklyEagerly() {
      console.warn('Scratch.gui.getBlocklyEagerly is patched in and does not work!');
      return this.getBlockly();
    }
  }
})();
```
